# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RogoCoreSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RogoCoreSample

#  pod 'RogoCore', "~> 1.0.2"
#
#pod 'CocoaMQTT',"~> 2.0.9"
pod 'CocoaMQTT'
pod 'nRFMeshProvision', '~> 3.0'
pod 'SwiftEntryKit', '~> 2.0'
pod 'DropDown'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end
